version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
    ports:
      - '3006:3006'
    volumes:
      - .:/home/node/app
      - node-modules:/home/node/app/node_modules
      - aws-credentials:/home/node/.aws
volumes:
  node-modules:
  aws-credentials:
