version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout

      - restore_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}

      - run:
          name: Print versions
          command: node --version && yarn --version

      - run:
          name: Install node packages
          command: yarn install

      - save_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: yarn test

      -run:
          name: Build package
          command: yarn package
